version: '3'
services:
  novaposhta-sdk:
      hostname: novaposhta-sdk
      build:
        context: .
        dockerfile: Dockerfile
      image: novaposhta/php-sdk:dev
      volumes:
        - .:/usr/src/novaposhta-sdk
      networks:
        - intranet

networks:
  intranet:
    driver: bridge
